const modes={normal:{source:"Supplied by inverter",path:"Inverter",bypass:"Available",detail:"Conditioned fictional UPS path displayed"},static:{source:"Supplied by internal bypass",path:"Internal bypass",bypass:"Carrying load",detail:"Internal bypass concept view selected"},maintenance:{source:"Supplied by external path",path:"External path",bypass:"Direct path",detail:"External maintenance concept view selected"}};
const safetyGate=document.querySelector("#safety-gate"),safetyCheck=document.querySelector("#safety-check"),enterButton=document.querySelector("#enter-simulator"),modeButtons=[...document.querySelectorAll("[data-mode]")],diagram=document.querySelector(".one-line"),viewedModes=new Set(["normal"]);let tourIndex=0;
const timeNow=()=>new Intl.DateTimeFormat([],{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date());
function addEvent(event,details){const row=document.createElement("div");row.className="event-row";[timeNow(),event,details].forEach(value=>{const cell=document.createElement("span");cell.textContent=value;row.appendChild(cell)});document.querySelector("#event-rows").prepend(row)}
function updateProgress(){const count=viewedModes.size;document.querySelector("#progress-copy").textContent=`${count} / 3 states viewed`;document.querySelector("#progress-fill").style.width=`${count/3*100}%`}
function selectMode(name,log=true){const mode=modes[name];if(!mode)return;diagram.dataset.currentMode=name;modeButtons.forEach(button=>{const active=button.dataset.mode===name;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});document.querySelector("#load-source").textContent=mode.source;document.querySelector("#status-path").textContent=mode.path;document.querySelector("#status-bypass").textContent=mode.bypass;viewedModes.add(name);updateProgress();if(log)addEvent("Concept state changed",mode.detail)}
safetyCheck.addEventListener("change",()=>{enterButton.disabled=!safetyCheck.checked});enterButton.addEventListener("click",()=>{safetyGate.classList.add("hidden");modeButtons[0].focus();addEvent("Simulator initialized","Non-procedural concept explorer started")});modeButtons.forEach(button=>button.addEventListener("click",()=>selectMode(button.dataset.mode)));
document.querySelector("#start-tour").addEventListener("click",()=>{const order=["normal","static","maintenance"];selectMode(order[tourIndex]);tourIndex=(tourIndex+1)%order.length});document.querySelector("#reset-tour").addEventListener("click",()=>{viewedModes.clear();viewedModes.add("normal");tourIndex=0;selectMode("normal",false);document.querySelector("#event-rows").replaceChildren();addEvent("Explorer reset","Returned to the initial fictional state")});document.querySelector("#clear-log").addEventListener("click",()=>document.querySelector("#event-rows").replaceChildren());updateProgress();

